print("--= boy_deploy =--")

require("ezekiel.plugins-setup")
require("ezekiel.core.options")
require("ezekiel.core.keymaps")
require("ezekiel.core.colorscheme")

require("ezekiel.plugins.comment")
require("ezekiel.plugins.nvim-tree")
require("ezekiel.plugins.lualine")
require("ezekiel.plugins.telescope")
require("ezekiel.plugins.nvim-cmp")
require("ezekiel.plugins.lsp.mason")
require("ezekiel.plugins.lsp.lspsaga")
require("ezekiel.plugins.lsp.lspconfig")

require("ezekiel.plugins.lsp.null-ls")
require("ezekiel.plugins.autopairs")
require("ezekiel.plugins.treesitter")
require("ezekiel.plugins.gitsigns")
